# Generated by Django 4.2.17 on 2025-01-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"verbose_name": "Dish", "verbose_name_plural": "Dishes"},
        ),
    ]
