# Generated by Django 4.2.16 on 2024-11-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_ingredient_dish_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
